### ISSUE TITLE
Create camera controls

### ISSUE THREAD

**Issue by vcwild** [vcwild/minirt#25]

**Comment by iaurg** [comment]
Your program must be able to apply translation and rotation transformation to cameras

Camera:
C -50.0,0,20 0,0,1 70
∗ identifier: C
∗ x,y,z coordinates of the view point: 0.0,0.0,20.6
∗ 3d normalized orientation vector. In range [-1,1] for each x,y,z axis:
0.0,0.0,1.0
∗ FOV : Horizontal field of view in degrees in range [0,180]
