### ISSUE TITLE
Create light controls

### ISSUE THREAD

**Issue by vcwild** [vcwild/minirt#26]

**Comment by iaurg** [comment]
Light management: spot brightness, hard shadows, ambiance lighting (objects are
never completely in the dark). You must implement Ambient and diffuse lighting

Light:
L -40.0,50.0,0.0 0.6 10,0,255
∗ identifier: L
∗ x,y,z coordinates of the light point: 0.0,0.0,20.6
∗ the light brightness ratio in range [0.0,1.0]: 0.6
∗ (unused in mandatory part)R,G,B colors in range [0-255]: 10, 0, 255
